# Generated by Django 2.1 on 2018-09-07 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_dt', models.DateField()),
                ('tran_desc', models.TextField()),
                ('tran_type', models.SmallIntegerField(default=1)),
                ('tran_amt', models.FloatField()),
                (
                    'category',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Category')),
            ],
        ),
    ]
